name: Create Release

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

jobs:
  create-tagged-release:
    #if: github.ref == 'refs/heads/master'
    name: Build and Create Tagged Release
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - name: Get tag
      run: echo ::set-output name=VERSION_TAG::${GITHUB_REF/refs\/tags\//}
      id: get_tag
    - run: echo ${{github.ref}}
    - name: Checkout source code
      uses: actions/checkout@v2
      with:
          fetch-depth: 0
          ref: ${{ github.ref }}
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - name: Bundle built files
      run: |
        mkdir -p ./temp/BendzDevtools
        cp ./{fxmanifest.lua,README.md,LICENSE} ./temp/BendzDevtools/
        cp -r ./{dist,html} ./temp/BendzDevtools
        cd ./temp && zip -r ../BendzDevtools.zip ./BendzDevtools
    - name: Create Release
      uses: "marvinpinto/action-automatic-releases@v1.2.1"
      id: auto_release
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN  }}"
        title: BendzDevtools | ${{ steps.get_tag.outputs.VERSION_TAG }}
        prerelease: false
        files: BendzDevtoolsV${{ steps.get_tag.outputs.VERSION_TAG }}.zip