# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
 # Prettier-Check:
  #  runs-on: ubuntu-latest
   # steps:
    #  - uses: actions/checkout@v2
     # - uses: actions/setup-node@v1
      #- run: npm install && npm run prettier-check
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - name: Bundle built files
      run: |
        mkdir -p ./temp/BendzDevtools/resources
        cp -r ./dist ./temp/BendzDevtools
        cd ./temp && zip -r ../BendzDevtools.zip ./BendzDevtools
    - name: Create Release
      uses: "marvinpinto/action-automatic-releases@v1.2.1"
      id: auto_release
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        title: BendzDevtools | ${{ steps.get_tag.outputs.VERSION_TAG }}
        prerelease: false
        files: BendzDevtools.zip

  
