name: Prettier Check

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  Prettier-Check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
    - run: npm install && npm run check-format
